(function() {var implementors = {};
implementors["parquet"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.Type.html\" title=\"enum parquet::basic::Type\">Type</a>",synthetic:false,types:["parquet::basic::Type"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.LogicalType.html\" title=\"enum parquet::basic::LogicalType\">LogicalType</a>",synthetic:false,types:["parquet::basic::LogicalType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.Repetition.html\" title=\"enum parquet::basic::Repetition\">Repetition</a>",synthetic:false,types:["parquet::basic::Repetition"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.Encoding.html\" title=\"enum parquet::basic::Encoding\">Encoding</a>",synthetic:false,types:["parquet::basic::Encoding"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.Compression.html\" title=\"enum parquet::basic::Compression\">Compression</a>",synthetic:false,types:["parquet::basic::Compression"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.PageType.html\" title=\"enum parquet::basic::PageType\">PageType</a>",synthetic:false,types:["parquet::basic::PageType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.SortOrder.html\" title=\"enum parquet::basic::SortOrder\">SortOrder</a>",synthetic:false,types:["parquet::basic::SortOrder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/basic/enum.ColumnOrder.html\" title=\"enum parquet::basic::ColumnOrder\">ColumnOrder</a>",synthetic:false,types:["parquet::basic::ColumnOrder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"parquet/file/properties/enum.WriterVersion.html\" title=\"enum parquet::file::properties::WriterVersion\">WriterVersion</a>",synthetic:false,types:["parquet::file::properties::WriterVersion"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
